US-2067 Will now use UTXOs as balance for bitcoin.
rsksmart/rif-wallet pull request #840
Opened 2023-12-11 14:36 UTC by Freshenext

Check screenshots:
![image](https://github.com/rsksmart/rif-wallet/assets/39339295/a9481748-c0bd-4513-a765-82b194a93df7)

![image](https://github.com/rsksmart/rif-wallet/assets/39339295/e84535c1-b47f-48d5-9d7f-5aa20b445a04)

2023-12-11 15:38 UTC, TravellerOnTheRun requested changes
All is good, only the naming is confusing,  I suggest to change it to something generic

2023-12-12 14:02 UTC, Freshenext commented on src/screens/send/TransactionForm.tsx
> +  const balanceIfAssetIsBtc = useMemo(
kk good to go

2023-12-12 14:59 UTC, TravellerOnTheRun approved these changes
Good to go!

2023-12-14 12:34 UTC, jessgusclark approved these changes

2023-12-14 12:34 UTC, merged