US-2068: User should be able to see a pending TX that was sent through WalletConnect
rsksmart/rif-wallet pull request #852
Opened 2023-12-20 02:51 UTC by rodrigoncalves

<img src="https://github.com/rsksmart/rif-wallet-libs/assets/4074139/d41b1344-ea0b-46e5-be1a-0e8dd248b3f9" width="300" /><img src="https://github.com/rsksmart/rif-wallet-libs/assets/4074139/7cd568b2-5413-4ae1-a867-0a4d283c3632" width="300" />

2023-12-20 13:12 UTC, jessgusclark commented
@rodrigoncalves Published: `@rsksmart/rif-wallet-adapters@1.0.3`

2023-12-20 15:10 UTC, Freshenext commented on src/screens/walletConnect/WalletConnect2Context.tsx
> +              try {
I think that we can create a function for this, and then call it here.
From line 201 to line 219, that way we can reuse it across the app if, in the future, we implement a normal wallet.

2023-12-20 17:02 UTC, Freshenext requested changes
Left some comments to address

2023-12-20 17:02 UTC, Freshenext commented on src/lib/utils.ts
> +export const createPendingTxFromWcResponse = async (
Rename to createPendingTxFromTransactionResponse (as it can apply to any TransactionResponse type, and not only WC specific - this is to bulletproof for the future)

2023-12-20 17:02 UTC, Freshenext commented on src/lib/utils.ts
> +  wcResponse: TransactionResponse,
Rename wcResponse to response

2023-12-20 17:02 UTC, Freshenext commented on src/lib/utils.ts
> +  { chainId, from, to }: { chainId: number; from: string; to: string },
chainId: number should be changed by the chainId that we currently support in the wallet - you can use ChainTypesByIdType

2023-12-20 17:02 UTC, Freshenext commented on src/lib/utils.ts
> +      ...(wcResponse as any),
I think it's forbidden to use the any type, what you can do is ...response then the missing properties you can add them as '', such as transactionIndex, txType, etc...

2023-12-20 17:14 UTC, rodrigoncalves commented on src/lib/utils.ts
> +  { chainId, from, to }: { chainId: number; from: string; to: string },
`const chainId = useAppSelector(selectChainId)` it returns an number. I'm just passing that along.

2023-12-21 00:58 UTC, Freshenext approved these changes
Great!

Pending Manual Testing.

2023-12-21 14:55 UTC, jormelCoin commented
It's maybe not related to this PR; nonetheless, I have a question:

After seeing the pending message as expected, it got disconnected from the web https://basic-sample.rlogin.identity.rifos.org/, but the connection on the device was kept.

Is it ok? or should I create a ticket that if it was disconnected from the web, it should happen the same on the device?

2024-01-05 16:12 UTC, jormelCoin approved these changes

2024-01-08 12:53 UTC, jessgusclark approved these changes

2024-01-08 12:54 UTC, merged