US-1480: Migrate RNS lookup to @rsksmart/rns-sdk
rsksmart/rif-wallet pull request #862
Opened 2024-01-11 03:28 UTC by rodrigoncalves

2024-01-16 14:42 UTC, jormelCoin requested changes
Please take a look at it since when writing the RNS and hitting the send button, nothing happens, but when I pass the address directly, it works.

2024-01-17 18:33 UTC, jormelCoin approved these changes
works as expected ✅

2024-01-18 12:27 UTC, jessgusclark requested changes
Can you remove the old package from the package.json and lock file? Thanks.

2024-01-22 12:04 UTC, jessgusclark approved these changes

2024-01-22 12:04 UTC, merged