US-2090: Transaction Summary - Issue with TX Hash Link Explorer Showing Incorrect Bitcoin Explorer Website
rsksmart/rif-wallet pull request #870
Opened 2024-01-23 15:01 UTC by rodrigoncalves

2024-01-25 14:37 UTC, jormelCoin commented
@rodrigoncalves, could you please check the BTC link on tesnet? This PR should work for both mainnet and tesnet; I just tested it and it currently works for mainnet but fails for tesnet. 

<img width="355" alt="Screenshot 2024-01-25 at 11 37 24" src="https://github.com/rsksmart/rif-wallet/assets/114427184/eaf3419e-8814-4098-8bf6-7045516e7ef9">

2024-01-25 14:38 UTC, jormelCoin requested changes
Mainnet
<img width="358" alt="Screenshot 2024-01-25 at 11 30 35" src="https://github.com/rsksmart/rif-wallet/assets/114427184/0046b3f7-af0c-4016-a982-ee5604241635">

Tesnet
<img width="356" alt="Screenshot 2024-01-25 at 11 38 28" src="https://github.com/rsksmart/rif-wallet/assets/114427184/7be6586f-37d9-4d46-a718-21ee69eeb07e">

2024-01-25 19:16 UTC, jormelCoin approved these changes
it works in a good way.

2024-01-29 14:16 UTC, jessgusclark approved these changes

2024-01-29 14:16 UTC, merged