Add RIF Faucet as a known address in testnet.
rsksmart/rif-wallet pull request #874
Opened 2024-01-26 12:55 UTC by jessgusclark

This should work for both the EOA and Relay versions as the address is the same.

Example:
![Screenshot 2024-01-26 at 2 54 20 PM](https://github.com/rsksmart/rif-wallet/assets/766679/3f4ec9f3-cc05-477e-9924-cae2b8c11fd7)

Merging into `us-2005`

2024-01-26 15:02 UTC, TravellerOnTheRun approved these changes
Looks good! Let's merge that one

2024-01-26 18:34 UTC, jormelCoin requested changes
This is how it looked before:
![IMG_C7102294550A-1](https://github.com/rsksmart/rif-wallet/assets/114427184/2aec8dcb-e72f-4eb7-add7-d6969ede6ef6)

This is how it looks in this PR:
<img width="344" alt="Screenshot 2024-01-26 at 15 32 57" src="https://github.com/rsksmart/rif-wallet/assets/114427184/a7cdd087-3dbc-4377-8a05-ff4d189f9429">

So, If I'm not wrong, the conversion displayed now is erroneous

2024-01-29 12:17 UTC, jessgusclark commented
@jormelCoin I can rebase again, but what you are seeing is not caused by this PR, that was done elsewhere.

2024-01-29 13:02 UTC, jormelCoin approved these changes

2024-01-29 13:39 UTC, merged