US-2157: Round USD conversions
rsksmart/rif-wallet pull request #890
Opened 2024-02-07 03:15 UTC by rodrigoncalves

As suggested by @TravellerOnTheRun, I decided to not only modify the existing `formatTokenValues` function, but split into 2 different functions (`formatTokenValue` and `formatFiatValue`) that each use a generic `formatNumber` function. This function expands the current implementation and now it should cover all different cases present in the application. 

Below are a few screenshots showing the implementation in action. Please let me know if I missed anything.

<img src="https://github.com/rsksmart/rif-wallet/assets/4074139/8e566ef2-76c6-40a3-be96-85a279e6baea" width="200" /> <img src="https://github.com/rsksmart/rif-wallet/assets/4074139/914098d0-bb0d-441d-b1ec-5604e2620a73" width="200" /> <img src="https://github.com/rsksmart/rif-wallet/assets/4074139/1410d9fe-15ea-4165-8a15-1955f6e1fd22" width="200" /> <img src="https://github.com/rsksmart/rif-wallet/assets/4074139/de84ed1e-18ed-4b38-bdad-19a0d9758ce9" width="200" /> <img src="https://github.com/rsksmart/rif-wallet/assets/4074139/c4b6866b-0985-41cc-97bf-8d6d8df95385" width="200" /> <img src="https://github.com/rsksmart/rif-wallet/assets/4074139/9e61d09e-7ec2-4374-8429-77abdadb8e4d" width="200" /> <img src="https://github.com/rsksmart/rif-wallet/assets/4074139/02910cf9-c83b-49a1-979c-450c7d83ab77" width="200" /> <img src="https://github.com/rsksmart/rif-wallet/assets/4074139/f05f92d2-ea7c-463d-bb1c-604388ca8b4b" width="200" /> <img src="https://github.com/rsksmart/rif-wallet/assets/4074139/5627bef5-45b2-4d15-8322-792748385c07" width="200" /> <img src="https://github.com/rsksmart/rif-wallet/assets/4074139/de47f023-884a-44cb-a4cb-aa57d8944638" width="200" />

2024-02-07 14:28 UTC, TravellerOnTheRun commented
@rodrigoncalves 
I've looked through the code and I don't like what I see:
First of all, the RBTC fee values will always show as `0.00` as it was before, because the value is `toFixed(2)`. I already added the function which `formatTokenValues` which already contains the logic for showing the values in a relatively nice-looking manner. How about you edit that? We can discuss how many digits we want after 0 but let's make a single source of truth for formatting values?

2024-02-07 14:56 UTC, rodrigoncalves commented
> @rodrigoncalves I've looked through the code and I don't like what I see: First of all, the RBTC fee values will always show as `0.00` as it was before, because the value is `toFixed(2)`. I already added the function which `formatTokenValues` which already contains the logic for showing the values in a relatively nice-looking manner. How about you edit that? We can discuss how many digits we want after 0 but let's make a single source of truth for formatting values?

Of course! That's why this PR is in draft, I'm still playing around with it. The `formatTokenValues` function seems to be a nice way to deal with token amounts due to different quantities of decimal places that we can have. However I didn't want to edit that function yet as all I need to do for a USD conversion is `toFixed(2)` and there you go. But I know for RBTC fee values cases (<$0.01), for example, it could be a problem.

2024-02-12 14:59 UTC, jessgusclark requested changes

2024-02-12 14:59 UTC, jessgusclark commented on src/screens/activity/ActivityRow.tsx
> +    const isAmountSmall = !usdBalance && !!price
This code is repeated a few times in this PR. However, this type of code shouldn't be at the component level, we should outsource it. 

Take a look at the existing functions for handling numbers in the shared/utils. I think there should be something that handles this,

2024-02-12 14:59 UTC, jessgusclark commented on src/ux/requestsModal/ReviewRelayTransaction/ReviewTransactionContainer.tsx
> -    const tokenUsd = convertTokenToUSD(Number(value), tokenQuote)
What was wrong with the convertTokenToUSD method? Does it be modified rather than reinventing the wheel locally in this file?

2024-02-20 11:36 UTC, TravellerOnTheRun requested changes

2024-02-20 11:36 UTC, TravellerOnTheRun commented on src/shared/utils/index.ts
> +const formatNumber = (
This function already exists, `formatTokenValues` modify that one please

2024-02-20 12:10 UTC, rodrigoncalves commented on src/shared/utils/index.ts
> +const formatNumber = (
I know. Be patient, I haven't finished the PR yet.

2024-02-22 08:10 UTC, TravellerOnTheRun requested changes
Some changes are still required for future proofing the app

2024-02-22 08:10 UTC, TravellerOnTheRun commented on src/screens/send/TransactionForm.tsx
> +          balance: formatUsdValue(convertTokenToUSD(numberAmount, tokenQuote)),
Why the values get formatted in the `TransactionForm`? It is users' input values. They should be seen as is, no?

2024-02-22 08:10 UTC, TravellerOnTheRun commented on src/screens/send/TransactionForm.tsx
> +    balance: formatUsdValue(0),
Question: why do you need to formate initial state?

2024-02-22 08:10 UTC, TravellerOnTheRun commented on src/screens/send/TransactionForm.tsx
> +            18,
I think decimal places should be less since it's in the button text

2024-02-22 08:10 UTC, TravellerOnTheRun commented on src/screens/transactionSummary/TransactionSummaryComponent.tsx
> +                    {fee.tokenValue} {fee.symbol}
I actually think, since `TransactionSummaryComponent` is the last in the chain, the value should be formatted here as it was previously since formatting is only really needed for display purpose. Same goes for other places, the actual component that will show the values should do the formatting since it is the one who renders stuff for users

2024-02-22 08:10 UTC, TravellerOnTheRun commented on src/shared/utils/index.test.ts
> +    expect(formatTokenValue('1234.5000')).toBe('1,234.5')
Maybe inserting one zero after value will be a good idea? Like `1,234.50`? Looks better in my opinion.

2024-02-22 08:10 UTC, TravellerOnTheRun commented on src/shared/utils/index.test.ts
> +    expect(formatUsdValue(0.0100000001)).toBe('$0.01')
Let's name the function `formatFiatValue`? We'll for sure introduce other currencies in the future.

2024-02-22 08:10 UTC, TravellerOnTheRun commented on src/shared/utils/index.ts
> +    return smallAmountDisplay
just return `<${sign}0.${'0'.repeat(decimalPlaces - 1)}1` since there are no other manipulations are done with that const

2024-02-22 08:10 UTC, TravellerOnTheRun commented on src/shared/utils/index.ts
> +export const formatUsdValue = (value: number | string): string =>
`formatFiatValue` and optionally pass the sign or rather second parameter as union like `'usd' | 'euro'`(but save it as shared type) to choose from. For now it can be just `usd` and default value will be `usd` but in the future we can just modify this and the function can be used for other currencies.

2024-02-22 08:10 UTC, TravellerOnTheRun commented on src/ux/requestsModal/ReviewBitcoinTransactionContainer.tsx
> +          symbol: '$',
This same `SupportedFiatCurrencies` can be used here for symbol to future proof this component

2024-02-22 08:10 UTC, TravellerOnTheRun commented on src/ux/requestsModal/ReviewBitcoinTransactionContainer.tsx
> +          usdValue: formatUsdValue(feeUsd),
This should be done in `TransactionSummary` as it is the thing user sees

2024-02-22 08:10 UTC, TravellerOnTheRun commented on src/screens/activity/ActivityRow.tsx
> +        totalToken: formatTokenValue(totalToken),
Same goes here: let the `TransactionSummary` do formatting, plus this logic should be moved out of here in one of my PRs as it belongs to the screen not the dumb component like `ActivityRow`

2024-02-22 08:10 UTC, TravellerOnTheRun commented on src/screens/activity/ActivityRow.tsx
> +  const amount = symbol.startsWith('BTC') ? value : formatTokenValue(value)
This is good

2024-02-22 08:10 UTC, TravellerOnTheRun commented on src/components/token/index.tsx
> +              {hide ? '\u002A\u002A\u002A\u002A\u002A' : secondValue.balance}
Why not formatting `secondValue.balance`?

2024-02-22 14:40 UTC, rodrigoncalves commented on src/screens/send/TransactionForm.tsx
> +          balance: formatUsdValue(convertTokenToUSD(numberAmount, tokenQuote)),
Second balance is not user's input. It's a readonly field.

2024-02-22 14:40 UTC, rodrigoncalves commented on src/screens/send/TransactionForm.tsx
> +    balance: formatUsdValue(0),
Because it will show the currency sign like "$0.00".

2024-02-22 14:41 UTC, rodrigoncalves commented on src/screens/send/TransactionForm.tsx
> +            18,
Agree. I'm removing that.

2024-02-22 14:44 UTC, rodrigoncalves commented on src/screens/transactionSummary/TransactionSummaryComponent.tsx
> +                    {fee.tokenValue} {fee.symbol}
Based in previous dissussions, I thought `TransactionSummaryComponent` should only display data, not formatting. But I agree with you in this case, I'll modify this.

2024-02-22 14:46 UTC, rodrigoncalves commented on src/shared/utils/index.test.ts
> +    expect(formatTokenValue('1234.5000')).toBe('1,234.5')
This is for token formatting, not USD. If I have 1.5 RBTC, there is no need to show as 1.50 RBTC, for example.

2024-02-22 14:48 UTC, rodrigoncalves commented on src/shared/utils/index.test.ts
> +    expect(formatUsdValue(0.0100000001)).toBe('$0.01')
We can create that function in the future by passing a parameter and then selecting the corresponding sign. For now we can leave it as is.

2024-02-22 14:49 UTC, rodrigoncalves commented on src/shared/utils/index.ts
> +    return smallAmountDisplay
OK

2024-02-22 14:51 UTC, rodrigoncalves commented on src/shared/utils/index.ts
> +export const formatUsdValue = (value: number | string): string =>
Ok it may work.

2024-02-22 14:52 UTC, rodrigoncalves commented on src/ux/requestsModal/ReviewBitcoinTransactionContainer.tsx
> +          symbol: '$',
Actually this symbol is not being used.

2024-03-04 07:27 UTC, TravellerOnTheRun requested changes

2024-03-04 07:27 UTC, TravellerOnTheRun commented on src/components/token/index.tsx
> +                ? formatUsdValue(secondValue.balance)
make it `formatFiatValue`?

2024-03-04 07:27 UTC, TravellerOnTheRun commented on src/ux/requestsModal/ReviewBitcoinTransactionContainer.tsx
> +import { formatTokenValue, formatUsdValue } from 'shared/utils'
Are those unused?

2024-03-04 07:27 UTC, TravellerOnTheRun commented on src/shared/utils/index.ts
> +export const formatUsdValue = (value: number | string): string =>
let's rename that to `formatFiatValue` to prepare for the future? We can change the values in components in the future PRs

2024-03-04 07:27 UTC, TravellerOnTheRun commented on src/ux/requestsModal/ReviewRelayTransaction/ReviewTransactionContainer.tsx
> +  formatUsdValue,
Is this unused?

2024-03-21 15:08 UTC, jormelCoin requested changes
It should be fixed in this PR.

![Screenshot 2024-03-21 at 11 43 00](https://github.com/rsksmart/rif-wallet/assets/114427184/6c00c470-d16f-41a9-a5be-d1c62faf2fcd)

2024-03-29 14:03 UTC, jormelCoin commented
I still see the NaN in Bitcoin transactions. 

@jessgusclark, when you get a chance, could you, please take a look? Rodrigo says it works well for him but for me fails since I still see the NaN.

2024-04-02 16:54 UTC, jormelCoin approved these changes
I carried out the tests and it worked very well both iOS and Android.

2024-04-12 12:07 UTC, jessgusclark approved these changes

2024-04-12 12:07 UTC, merged