US-2158 Make sure that we use the same strategy when working with fee
rsksmart/rif-wallet pull request #892
Opened 2024-02-08 06:18 UTC by TravellerOnTheRun

https://github.com/rsksmart/rif-wallet/assets/47615361/fe5d521e-ee29-42a9-8270-cdb305300874

This is my take on making sure the app uses more or less the same way of getting the fee.

2024-02-09 14:59 UTC, jormelCoin requested changes
I was able to send RIF, when I try to send rdoc or RBTC doesn't work. When hitting the button spend much time waiting and doing nothing.

https://github.com/rsksmart/rif-wallet/assets/114427184/99429934-f2c7-4914-b0d7-0af15a0f0356

2024-02-20 11:25 UTC, TravellerOnTheRun commented
> I was able to send RIF, when I try to send rdoc or RBTC doesn't work. When hitting the button spend much time waiting and doing nothing.
> 
>  20240209_115248.mp4

Now it shoudl work. Please, note that when using Relay(`USE_RELAY === true`) the fee for RBTC will be in RIF

2024-02-20 15:08 UTC, jormelCoin approved these changes

2024-03-01 12:24 UTC, jessgusclark approved these changes

2024-03-01 12:24 UTC, merged